### ISSUE TITLE
Please add

### ISSUE THREAD

**Issue by porushh** [ilyas-it83/CloudComparer#1]
Please add a new column for the Oracle cloud.

**Comment by ilyas-it83** [comment]
Oracle is also on the radar, however i'm new to Oracle which is the bottleneck here, if you are willing to help, we can jointly add Oracle Services into the comparison

**Comment by porushh** [comment]
Sure, I can work with you on this. I am currently not employed by Oracle.

Regards,

Porus.

**Comment by porushh** [comment]
Can you send me a spreadsheet with the existing columns, and I can work on
that with the new column.

Regards,

Porus.

**Comment by ilyas-it83** [comment]
Hi Porussh, I have added a json file under data folder, kindly add another entry for oracle under each category to include oracle services in the comparison list

**Comment by porushh** [comment]
In the data folder there is a CloudComparer.xlsx file, can that be edited
directly?

Regards,

Poris.

**Comment by ilyas-it83** [comment]
Hi Poris,

Yes, you can directly edit the Json file, but you have to make sure certain things. Can we connect over Skype or Google hangout, i can take you through few important things.

**Comment by porushh** [comment]
No, I wanted to directly change the spreadsheet. It makes it easier to
share with other people if I want to double confirm what things are in
Oracle. All people are not developers and dont work with Json.

Regards,

Porus.

**Comment by ilyas-it83** [comment]
Hi Porus, I can understand the problem, so what i have done here is i have placed an excel sheet and highlighted the required information from oracle against the competing services from Azure and AWS. If you can fill and upload, i can manually copy and update it in JSON document. Please find the excel here https://github.com/ilyas-it83/CloudComparer/blob/master/data/CloudComparer.xlsx

**Comment by porushh** [comment]
Ok Ilyas.

Regards,

Porus.

**Comment by porushh** [comment]
I put in some parts in the spreadsheet. Now I have sent it to an Oracle
contact to unofficially put some of the blanks.
Will let you when he returns it, they normally take some time,

Regards,

Porus.

**Comment by ilyas-it83** [comment]
Hi porus, so nice of you... Respect your effort.

Let's wait untill they come back.

Thanks
Ilyas

**Comment by porushh** [comment]
Thanks Ilyas. I am not totally familiar with AWS services nor with Oracle
IaaS, so didnt know which related to which, I put in some of the database
comparisons. For the IaaS and other parts, the Oracle IaaS people needs to
verify. By the way some rows will be added, for the things that Oracle has
and which AWS doesnt have. Such as the bare metal service from Oracle, and
the exadata cloud service. There are also a lot of SaaS from Oracle that
AWS doesnt have. Want to make it a fair comparison.

Regards,

Porus.

**Comment by ilyas-it83** [comment]
Closing the issue as there are no action

**Comment by danielehrlich** [comment]
I just saw this thread as I was changing email clients and going through all my old emails.

I left Oracle a few days ago to go to work with an AWS partner. I still remember everything. I will look at this.
