### ISSUE TITLE
Please add the following

### ISSUE THREAD

**Issue by mictsi** [ilyas-it83/CloudComparer#10]
Hi, 

Like the cloudcomparer. 

Could you add the following to the cloudcomparer.

Azure database for Mysql (Preview) | https://azure.microsoft.com/en-us/services/mysql/
Azure database for PostgreSQL (Preview) | https://azure.microsoft.com/en-us/services/postgresql/

And changed the name of documentdb to cosmosdb and possibliy add graph database as a database alternative

**Comment by ilyas-it83** [comment]
Hi @mictsi,

Thanks for pointing out!
Added the highlighted service.

Regards
Ilyas F
