### ISSUE TITLE
Provide clarification about the meaning of the crossed red circles mean

### ISSUE THREAD

**Issue by atiradocc** [ilyas-it83/CloudComparer#106]
Provide a legend or clarification about the meaning of the cross red circle icon given the service is available for the given provider and lack thereof is shown with an empty cell.

Was it meant as a way to convey partial coverage?

![Screen Shot 2020-10-01 at 10 34 57 AM](https://user-images.githubusercontent.com/55715751/94823392-ca2e1d00-03d1-11eb-90f6-8355a9150e0e.png)

**Comment by ilyas-it83** [comment]
@atiradocc, These are basically no images... Either there was no logo at the time of writing this project or I was not able to find it. Appreciate if you could raise a PR with the icons.

**Comment by ilyas-it83** [comment]
Closing the images with an updated image which highlights unavailability of images.
