### ISSUE TITLE
More missing Google Cloud mappings

### ISSUE THREAD

**Issue by petermark** [ilyas-it83/CloudComparer#13]
The following mappings are also missing/outdated from the comparison tool:

 - Big Data/Genomics: [Google Genomics](https://cloud.google.com/genomics/)
 - Big Data/Data Loss Prevention: [Data Loss Prevention API](https://cloud.google.com/dlp/)
 - Migration Services/Small Scale Data Transfer Service: [Offline Media Import/Export](https://cloud.google.com/storage/docs/offline-media-import-export)
 - Migration Services/Cloud to Cloud Migration: [Transfer Service](https://cloud.google.com/storage/transfer/)
 - Artificial Intelligence/Video Intelligence AI: [Cloud Video Intelligence API](https://cloud.google.com/video-intelligence/)
 - Artificial Intelligence/Jobs Analysis AI: [Cloud Jobs API](https://cloud.google.com/jobs-api/)
 - Mobile Services/Mobile App Development Services: [Firebase](https://firebase.google.com/)
 - Mobile Services/Web API Management Service: [Apigee](https://apigee.com/api-management/)
   - This is in addition to Cloud Endpoints
 - Mobile Services/Web/Mobile Authentication Services: [Firebase Authentication](https://firebase.google.com/products/auth/)
 - Mobile Services/Consolidated Manag of Multiple Cloud Accounts: [Google Analytics for Firebase](https://firebase.google.com/products/analytics/)
 - Mobile Services/Mobile App Software Development Kit: [Firebase SDK](https://firebase.google.com/docs/libraries/)
 - Mobile Services/Application Services: [Cloud Functions for Firebase](https://firebase.google.com/products/functions/)
   - This is in addition to App Engine
- Mobile Services/Real Time Database: [Firebase Realtime Database](https://firebase.google.com/products/database/)
- Mobile Services/Crash Reporting: [Firebase Crash Reporting](https://firebase.google.com/products/crash/)
- Mobile Services/Perfomance Monitoring: [Firebase Perfomance](https://firebase.google.com/products/performance/)
- Mobile Services/Deep Links: [Firebase Dynamic Links](https://firebase.google.com/products/dynamic-links/)
- Mobile Services/Mobile Notifications: [Firebase Cloud Messaging](https://firebase.google.com/products/cloud-messaging/)
- Mobile Services/Remote Configuration: [Firebase Remote Config](https://firebase.google.com/products/remote-config/)
- Mobile Services/App Indexing: [Firebase App Indexing](https://firebase.google.com/products/app-indexing/)
- Application Services/API Management Service: [Google Cloud Endpoints](https://cloud.google.com/endpoints/), [Apigee](https://apigee.com/api-management/)
- Application Services/Media Transcoders: [Anvato](http://www.anvato.com/)
- Application Services/Mobile Analytics: [Google Analytics for Firebase](https://firebase.google.com/products/analytics/)
 - Application Services/Notification Services: [Google Cloud Pub/Sub](https://cloud.google.com/pubsub/)
 - Business Productivity/Office Document Solutions: [Google Docs](https://gsuite.google.com/products/docs/), [Google Sheets](https://gsuite.google.com/products/sheets/), [Google Slides](https://gsuite.google.com/products/slides/)
   - These services make up document solutions
 - Business Productivity/Email: [Gmail](https://gsuite.google.com/products/gmail/)
 - Business Productivity/Calendar: [Google Calendar](https://gsuite.google.com/products/calendar/)
 - Business Productivity/Forms: [Google Forms](https://gsuite.google.com/products/forms/)
 - Business Productivity/Team Sites: [Google Sites](https://gsuite.google.com/products/sites/)
 - Business Productivity/Video Conferencing: [Hangouts Meet](https://gsuite.google.com/products/meet/)
 - Business Productivity/Digital Collaboration: [Jamboard](https://gsuite.google.com/products/jamboard/)
 - Business Productivity/Shared File Storage: [Google Drive](https://gsuite.google.com/products/drive/)
 - Business Productivity/File Search: [Cloud Search](https://gsuite.google.com/products/cloud-search/)
 - Business Productivity/Email Archive: [Vault](https://gsuite.google.com/products/vault/)
 - Software Marketplace/Cloud Marketplace: [Orbitera](http://www.orbitera.com/)
   - This is in addition to Cloud Launcher

**Comment by ilyas-it83** [comment]
Only products from the respective cloud providers managed products listing can be qualified for comparison. I have updated the list with most of the recent announcements from Google. For now, im closing the issue, plz re-open if required.
