### ISSUE TITLE
Add AWS App Runner And GCP Cloudrun

### ISSUE THREAD

**Issue by julianopoklen** [ilyas-it83/CloudComparer#143]
Hello Team,

Please add AWS App Runner and GCP Clourun.

AWS App Runner and GCP Cloudrun are similars to Azure Container Instances. They are all services as Containers without infrastructure.

My suggestion is to create a new category called "Containers" and include "Containers without infrastructure". Move the other container services items from the "compute" category to this new category.

https://cloud.google.com/free/docs/aws-azure-gcp-service-comparison
https://cloud.google.com/run
https://aws.amazon.com/about-aws/whats-new/2021/05/aws-announces-aws-app-runner
https://aws.amazon.com/apprunner

Thanks
Juliano

**Comment by kaplanan** [comment]
Resolved with #157
