### ISSUE TITLE
Page does not render https://comparecloud.in/

### ISSUE THREAD

**Issue by pexus** [ilyas-it83/CloudComparer#147]
Page : https://comparecloud.in/ does not render. Not sure if this an issue with the source or the server. It used to work
I don't see the table of comparison. It only shows the discuss discussion but no comparison table.

**Comment by siegenv** [comment]
Same with me

**Comment by m8ram** [comment]
Works fine for me on September 29. Perhaps you can check again?
Maybe also check https://downforeveryoneorjustme.com/comparecloud.in to see if it is a local issue or not.
