### ISSUE TITLE
Amazon Lambda is not equivalent with Azure Cloud Services or Logic Apps

### ISSUE THREAD

**Issue by seyedsepehr** [ilyas-it83/CloudComparer#17]
Amazon Lambda is the serverless compute service in AWS. Its equivalent is Azure Functions.
Azure Cloud Service and Logic Apps are incorrectly mapped to Amazon Lambda in the comparison.

Azure Cloud Services is much more closer to Amazon Elastic Beanstalk. In anyway it has no capability for serverless workloads.

Azure App Service Logic Apps is a workflow management service, similar to Amazon SWF and Amazon StepFunctions. Although Logic Apps capabilities are far beyond those offered by SWF or StepFunctions, at least the overall purpose is the same.

Azure App Service API Apps may be compared with AWS Lambda, because both can host backend REST APIs.

**Comment by ilyas-it83** [comment]
Updated as per the suggestions!

**Comment by JasonMrX** [comment]
Seems like a very old thread.. but I just wanna bring up that, why doesn't Azure Function matched with AWS Lambda?
