### ISSUE TITLE
AWS Glacier is not equivalent with Azure Cool Storage

### ISSUE THREAD

**Issue by seyedsepehr** [ilyas-it83/CloudComparer#18]
AWS Glacier is an archiving service implemented using magnetic tapes with very cheap price on the cost of several hours of lead time required for retrieval. Currently there is no equivalent service in Azure.

Azure Blobs Cool Storage is equivalent with AWS S3 Infrequently Accessed layer (IA). It allows discounts for infrequently accessed data but costs more for frequently accessed data. An important difference between both AWS S3 IA and Azure Blobs Cool Storage with AWS Glacier is that Glacier needs several hours of lead time for retrieval of data whereas both S3 IA and Blobs Cool Storage allow instance retrieval of data upon request.

**Comment by Dolganoff** [comment]
Hello, 
Azure has the "true" archive storage now also, released recently.
https://azure.microsoft.com/en-us/services/storage/archive/
It's this one that is equivalent to AWS glacier.

Regards

**Comment by ilyas-it83** [comment]
@seyedsepehr  & @Dolganoff  Thanks for the comments. Updated Azure Archive Storage against glacier.
