### ISSUE TITLE
Parameter stores and compute configuration delivery?

### ISSUE THREAD

**Issue by jeking3** [ilyas-it83/CloudComparer#198]
I don't see any information about AWS SSM Parameter Store for delivering configuration to instances, containers, etc.
Azure has App Configutation key-value storage for this.
GCP doesn't appear to have anything for this.

Thoughts?

**Comment by ilyas-it83** [comment]
@jeking3, thanks for the question. The comparecloud captures the cloud services and doesn't go in detail about each and every feature of the list services.  Hope this helps.
