### ISSUE TITLE
Azure - Include machine learning frameworks

### ISSUE THREAD

**Issue by nateaveryg** [ilyas-it83/CloudComparer#206]
Additional Azure Machine learning frameworks should be included - 
PyTorch
TensorFlow
scikit-learn
XGBoost
LightGBM

per Azure documentation: https://docs.microsoft.com/en-us/azure/machine-learning/overview-what-is-azure-machine-learning

**Comment by ilyas-it83** [comment]
Hi @nateaveryg, Thanks for the suggestion, however the cloud comparison captures the high level services, but doesnt get into each and every features or capabilities of these services, hence its better to stay at this level.  Please feel free to further comment.
