### ISSUE TITLE
Added other Google Cloud Services

### ISSUE THREAD

**Issue by bjfjallen** [ilyas-it83/CloudComparer#207]
Made updates for Workflows, EventArc and CloudRun.  I merged in the changes and submitted a pull request.

**Comment by ilyas-it83** [comment]
@bjfjallen, thanks for your interest in contributing to this repo, however i dont see the PR yet. Could you please cross check once again.

**Comment by bjfjallen** [comment]
Sorry about that.  It closed my pull request when I did the automatic merge
that was recommended.  Here is my pull request
<https://github.com/ilyas-it83/CloudComparer/pull/208> (all related to
updates for Google Cloud Services).
