### ISSUE TITLE
missing cloud providers

### ISSUE THREAD

**Issue by omargad** [ilyas-it83/CloudComparer#223]
the following cloud services are not in the cloud comparison yet:
Tencent Cloud
CloudFlare 
Digital Ocean
Salesforce
VMware Cloud 
RedHat OpneShift
Heroku cloud
Linode
OVHcloud
Cloudways
Rackspace
GearHost
Orange Public Cloud

**Comment by ilyas-it83** [comment]
@omargad, there are 100s of cloud to list, but given the wider adoption of the public cloud and its completeness the community has chosen only the top 5 public clouds from the Gartner magic quadrants. You may fork this repo and add other clouds.
