### ISSUE TITLE
Azure Bare Metal

### ISSUE THREAD

**Issue by 13Amand** [ilyas-it83/CloudComparer#35]
Azure provides large instances as bare metal servers.

**Comment by ilyas-it83** [comment]
I dont think Azure Offers Bare Metal Servers in their cloud offering. If you think i'm wrong please share the link of the product page in Azure Documentation or Feature page.

**Comment by 13Amand** [comment]
Yes, they do. Please find the link as follows

https://docs.microsoft.com/en-us/azure/virtual-machines/workloads/sap/hana-overview-architecture

**Comment by ilyas-it83** [comment]
Thanks @13Amand , Looks like it only supports SAP Workload now(Included now).  Look forward for more such catches!
