### ISSUE TITLE
Event Grid is missing from Azure for Notification Services category

### ISSUE THREAD

**Issue by SeanFeldman** [ilyas-it83/CloudComparer#37]
[Event Grid service](https://azure.microsoft.com/en-gb/services/event-grid/)

![image](https://user-images.githubusercontent.com/1309622/37567498-8b356e16-2a8d-11e8-8735-b74d1e7036a1.png)

**Comment by ilyas-it83** [comment]
Published. Please check!

**Comment by SeanFeldman** [comment]
@ilyas-it83 `Category: Mobile services` doesn't seem right. I'd rather put it under `Application Services: Notification Services`.

**Comment by ilyas-it83** [comment]
I do agree, few services can be better listed under App Services, however most other services like "Mobile Analytics" doesnt suite app services IMHO, can you call out the ones that you think are better under app services?

**Comment by SeanFeldman** [comment]
Microsoft has done a good job at classifying Azure services [here](https://azure.microsoft.com/en-us/services/).

**Comment by ilyas-it83** [comment]
Thanks for the info!
