### ISSUE TITLE
No Icons for Oracle Cloud

### ISSUE THREAD

**Issue by danielehrlich** [ilyas-it83/CloudComparer#4]
I'm going to work on getting the icons for you @ilyas-it83.

I work at Oracle on the Oracle Cloud not surprisingly.

Also I will give you the mappings to other services as well, which you can see sort of done here: [https://github.com/danielehrlich/OracleCloudCompareMatrix](https://github.com/danielehrlich/OracleCloudCompareMatrix)

**Comment by ilyas-it83** [comment]
Hi Daniel, Can i have the Oracle Logos for the individual services as well as the mappings please.

**Comment by danielehrlich** [comment]
Just sent to your email.

**Comment by ilyas-it83** [comment]
Hi Daniel,

 Could you please also share the other colored icons to see which colors
suit the best.

Thanks
Ilyas F

**Comment by ilyas-it83** [comment]
Hi Daniel,

Info on Oracle cloud has been committed to the repo. I could not find
images for few services, hence i skipped those. Kindly review and let me
know if you want to see anymore changes.

Thanks
Ilyas F

**Comment by danielehrlich** [comment]
Do you have a link to the running site?

**Comment by ilyas-it83** [comment]
Hi Daniel,

Please find the link below.

https://ilyas-it83.github.io/CloudComparer/

Thanks
Ilyas F
