### ISSUE TITLE
IBM Cloud

### ISSUE THREAD

**Issue by owhc** [ilyas-it83/CloudComparer#40]
1. Batch Jobs : Workload Scheduler [https://console.bluemix.net/catalog/services/workload-scheduler](url)
2. Long Term Cold Storage: Cloud Object Storage , type : ColdVault [https://console.bluemix.net/docs/services/cloud-object-storage/basics/classes.html#what-are-the-classes-](url)
3. In-Memory Data Store: Compose for Redis [https://console.bluemix.net/catalog/services/compose-for-redis](url)
4. Small Scale Data Transfer Service: Data Transfer Service [https://console.bluemix.net/docs/infrastructure/DataTransferService/index.html#getting-started-with-data-transfer-service](url)
5. Large Scale Data Transfer Solution(Petabyte Scale): Massive Data Migration Service [https://console.bluemix.net/docs/infrastructure/mass-data-migration/index.html#getting-started-with-ibm-cloud-mass-data-migration](url)
6. Global Traffic Management : Cloud Internet Services : [https://console.bluemix.net/catalog/services/internet-services](url)

Please allow me edit IBM Cloud portion. A lot of miss items

**Comment by ilyas-it83** [comment]
Added these services against IBM. Closing!
