### ISSUE TITLE
Consolidated Management of Multiple Accounts

### ISSUE THREAD

**Issue by kylecweeks** [ilyas-it83/CloudComparer#48]
Azure supports a hybrid EA / Pay as you go subscription management model well above the subscription level. In my opinion, an Subscription is the equivalent of an AWS Account.

The core concepts of Security, Identity, and compliance as used per the AWS Org model is achieved as below.

https://docs.microsoft.com/en-us/azure/azure-resource-manager/management-groups-overview

**Comment by ilyas-it83** [comment]
Good One. Updated!
