### ISSUE TITLE
IBM Cloud: assigning AI APIs to the correct category

### ISSUE THREAD

**Issue by arlemi** [ilyas-it83/CloudComparer#52]
I'm a Developer Advocate @IBM and while reading through the list of services I found a few services that were not assigned to the right category or didn't have the right hyperlink.

- Speech to Text should be moved from **Language Processing AI** to **Speech Recognition AI**
- Retrieve and Rank has been deprecated and should be removed from the **Image Recognition AI** category
- Personality Insights should be moved from I**mage Recognition AI** to **Language Processing AI**
- In the **Chatbot** category (under Application Services), it should be redirecting to [Watson Assistant](https://console.bluemix.net/catalog/services/watson-assistant-formerly-conversation)

Let me know if you disagree or need more information on any of these points! 

And thanks for the great work on that comparison. 👍

**Comment by ilyas-it83** [comment]
Hi @arlemi, Appreciate your comments,  please go ahead and issue a pull request and look for "services.json" file inside the data folder, go ahead and alter the services and commit it. I shall then review and commit. Thanks

**Comment by arlemi** [comment]
Done, cheers! I will have a look at the other areas during this week (I've spotted a few dead links and misplaced services), should I PR directly or open an issue here first?

**Comment by ilyas-it83** [comment]
Hi Arlemi,

Please go ahead with pr directly...


Thanks
Ilyas
