### ISSUE TITLE
Adding Apache Foundation Solution

### ISSUE THREAD

**Issue by Sveder** [ilyas-it83/CloudComparer#7]
Even though it is not a cloud service per-se, Apache Foundation has a lot of tools that compare (and sometimes are the base for) the other cloud services. What do you think? Is this something you'd include, if I submit a PR?

**Comment by ilyas-it83** [comment]
Hi Sveder, The actual intention of the project is to mainly compare the services offered by the major public cloud providers, but not to compare the open source projects. Let me know if you want to contribute to this project.
